### ISSUE TITLE
It say 160 Bitcoin Addresses are loaded

### ISSUE THREAD

**Issue by Prophet1984** [Mizogg/Tkinter-Power-Mini#1]
![1](https://user-images.githubusercontent.com/115896258/208125633-2bb35264-9ae5-4763-95d0-91931bb00e24.jpg)
Why does it say 160 Bitcoin Addresses are loaded but in the folder there is no Addresses file that i can custom change

**Comment by Mizogg** [comment]
There is a file called btc.bf this is the database file. The current file on GitHub only has 160 puzzle addresses included. GitHub only allows 25MB max upload. Download a newer bigger database from any of the links below and rename to btc.bf.

Great telegram group to get upto date files CryptoCrackers https://t.me/CryptoCrackersUK and https://t.me/Blockchain_BTC_ETH_DUMPS

**Comment by Prophet1984** [comment]
Thank you very much!
