### ISSUE TITLE
Cbloom

### ISSUE THREAD

**Issue by theroyaledico** [Mizogg/Tkinter-Power-Mini#2]
Hello, 

I can't use Cbloom in files. 
It marks me "Ошибка. Слишком много параметров.
Exit code: 1" 
How to make it work and modify Btc.bf and Eth.bf?

**Comment by Tfoutu** [comment]
Cbloom.py File_TXT.txt File_txt.bf

**Comment by Mizogg** [comment]
Cbloom.py converts txt file database to a bloomfilter database.  If your already on Telegram grab them already made from here https://t.me/Blockchain_BTC_ETH_DUMPS
